# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'OneContact' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for OneContact
  pod 'Kanna', '~> 1.1.0'

  target 'OneContactTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'OneContactUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
