# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'oneContact' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for oneContact
  pod 'Kanna', '~> 1.1.0'

  target 'oneContactTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'oneContactUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
